---
- name: Deploy Prometheus and Grafana Monitoring Stack
  hosts: all
  become: yes
  vars:
    mon_dir: "/home/ubuntu/monitoring"

  tasks:
    - name: 1. Ensure monitoring directory exists
      ansible.builtin.file:
        path: "{{ mon_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: 2. Copy Monitoring configuration files
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../monitoring/{{ item }}"
        dest: "{{ mon_dir }}/{{ item }}"
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      loop:
        - docker-compose.yml
        - prometheus.yml

    - name: 3. Launch Prometheus & Grafana stack
      ansible.builtin.command:
        cmd: docker compose up -d --pull always --remove-orphans
        chdir: "{{ mon_dir }}"